#ifndef LEDHARDWARE_H_INCLUDED
#define LEDHARDWARE_H_INCLUDED

/* LED auf Basisplatine */
#define LEDROT_PORT PORTA
#define LEDROT_PIN  PIN2_bm
#define LEDGRUEN_PORT PORTA
#define LEDGRUEN_PIN  PIN3_bm
/* RGB-LED auf Displayplatine */
#define LEDRGB_GRUEN_PORT PORTA
#define LEDRGB_GRUEN_PIN  PIN6_bm
#define LEDRGB_ROT_PORT PORTA
#define LEDRGB_ROT_PIN  PIN7_bm
#define LEDRGB_BLAU_PORT PORTB
#define LEDRGB_BLAU_PIN  PIN0_bm
/* Beeper Displayplatine */
#define BEEPER_PORT PORTA
#define BEEPER_PIN  PIN4_bm
/* Dimmer Displayplatine */
#define DIMMER_PORT PORTE
#define DIMMER_PIN  PIN2_bm


#define LEDROTSETUP LEDROT_PORT.DIRSET=LEDROT_PIN
#define LEDROT_ON   LEDROT_PORT.OUTCLR=LEDROT_PIN
#define LEDROT_OFF  LEDROT_PORT.OUTSET=LEDROT_PIN
#define LEDROT_TOGGLE  LEDROT_PORT.OUTTGL=LEDROT_PIN

#define LEDGRUENSETUP LEDGRUEN_PORT.DIRSET=LEDGRUEN_PIN
#define LEDGRUEN_ON   LEDGRUEN_PORT.OUTCLR=LEDGRUEN_PIN
#define LEDGRUEN_OFF  LEDGRUEN_PORT.OUTSET=LEDGRUEN_PIN
#define LEDGRUEN_TOGGLE  LEDGRUEN_PORT.OUTTGL=LEDGRUEN_PIN

#define LEDRGB_GRUENSETUP LEDRGB_GRUEN_PORT.DIRSET=LEDRGB_GRUEN_PIN
#define LEDRGB_GRUEN_ON   LEDRGB_GRUEN_PORT.OUTCLR=LEDRGB_GRUEN_PIN
#define LEDRGB_GRUEN_OFF  LEDRGB_GRUEN_PORT.OUTSET=LEDRGB_GRUEN_PIN
#define LEDRGB_GRUEN_TOGGLE  LEDRGB_GRUEN_PORT.OUTTGL=LEDRGB_GRUEN_PIN

#define LEDRGB_ROTSETUP LEDRGB_ROT_PORT.DIRSET=LEDRGB_ROT_PIN
#define LEDRGB_ROT_ON   LEDRGB_ROT_PORT.OUTCLR=LEDRGB_ROT_PIN
#define LEDRGB_ROT_OFF  LEDRGB_ROT_PORT.OUTSET=LEDRGB_ROT_PIN
#define LEDRGB_ROT_TOGGLE  LEDRGB_ROT_PORT.OUTTGL=LEDRGB_ROT_PIN

#define LEDRGB_BLAUSETUP LEDRGB_BLAU_PORT.DIRSET=LEDRGB_BLAU_PIN
#define LEDRGB_BLAU_ON   LEDRGB_BLAU_PORT.OUTCLR=LEDRGB_BLAU_PIN
#define LEDRGB_BLAU_OFF  LEDRGB_BLAU_PORT.OUTSET=LEDRGB_BLAU_PIN
#define LEDRGB_BLAU_TOGGLE  LEDRGB_BLAU_PORT.OUTTGL=LEDRGB_BLAU_PIN

#define BEEPERSETUP BEEPER_PORT.DIRSET=BEEPER_PIN
#define BEEPER_OFF  BEEPER_PORT.OUTCLR=BEEPER_PIN
#define BEEPER_ON   BEEPER_PORT.OUTSET=BEEPER_PIN
#define BEEPER_TOGGLE  BEEPER_PORT.OUTTGL=BEEPER_PIN

#define DIMMERSETUP DIMMER_PORT.DIRSET=DIMMER_PIN
#define DIMMER_ON  DIMMER_PORT.OUTSET=DIMMER_PIN
#define DIMMER_OFF   DIMMER_PORT.OUTCLR=DIMMER_PIN
#define DIMMER_TOGGLE  DIMMER_PORT.OUTTGL=DIMMER_PIN

#endif // LEDHARDWARE_H_INCLUDED
