#ifndef MYCONSTANTS_H_INCLUDED
#define MYCONSTANTS_H_INCLUDED

/*
 * myConstants.h
 *
 * Created: 24.05.2018 19:24:50
 *  Author: chrak_2
 */

#define BROADCAST "BR"

enum{HEAT_OFF=0,HEAT_ON,HEAT_AUTO};
enum{DISPLAY_SLEEP=0,DISPLAY_MAIN,DISPLAY_CHOICE,DISPLAY_SETVALUE,DISPLAY_NONSENSE};
enum{FAN_STATUS_OFF,FAN_STATUS_1,FAN_STATUS_2,FAN_STATUS_AUTO,FAN_STATUS_UNVALID = 255};

#endif // MYCONSTANTS_H_INCLUDED
